import numpy as np
print("===== Exercise 1: Array Indexing =====")
arr = np.array([5, 10, 15, 20, 25, 30])     
print("Array:", arr)
print("First Element:", arr[0])
print("Last Element:", arr[-1])
print("Third Element:", arr[2])
print("\n===== Exercise 2: Array Slicing =====")
print("First Three Elements:", arr[:3])
print("Last Three Elements:", arr[-3:])
print("Every Second Element:", arr[::2])
print("\n===== Exercise 3: Reshaping Arrays =====")
arr2 = np.arange(1, 13)
print("Original Array:")
print(arr2)
print("\nReshape (3 x 4):")
print(arr2.reshape(3, 4))
print("\nReshape (2 x 6):")
print(arr2.reshape(2, 6))
print("\nReshape (6 x 2):")
print(arr2.reshape(6, 2))
print("\n===== Exercise 4: 2D Array =====")
matrix = np.array([[11, 22, 33],
                   [44, 55, 66]])
print(matrix)
print("First Element:", matrix[0, 0])
print("Third Element:", matrix[0, 2])
print("Middle Element:", matrix[1, 1])
print("First Row:", matrix[0, :])
print("Second Column:", matrix[:, 1])
print("\n===== Day 2 Mini Task =====")
marks = np.array([78, 85, 90, 67, 88, 95, 72, 80])
print("Original Marks:")
print(marks)
print("First Student Mark:", marks[0])
print("Last Student Mark:", marks[-1])
print("Top 5 Marks:")
print(marks[:5])
print("Every Second Mark:")
print(marks[::2])
print("Marks Reshaped (2 x 4):")
print(marks.reshape(2, 4))
print("\n===== Array Information =====")
print("Shape:", marks.shape)
print("Dimensions:", marks.ndim)
print("Size:", marks.size)
