file = open("data.txt","r")
print(file.read())
file.close()
file = open("data.txt""","a")
file.write("python")
file.close()
file = open("data.txt","w")
file.write("programming")
file.close()
