import numpy as np
import pandas as pd
print("CREATE NUMPY ARRAY")
data = np.array([10,20,30,40,50])
print(data)
print("------")
print("CONVERT TO DATAFRAME")
df = pd.DataFrame(data, columns=["Numbers"])
print(df)
print("------")
print("SUM")
print(np.sum(data))
print("------")
print("MAXIMUM")
print(np.max(data))
print("------")
print("MINIMUM")
print(np.min(data))
print("------")
print("AVERAGE")
print(np.mean(data))
