import numpy as np

print("CREATE ARRAY")
a = np.array([1,2,3,4])
print(a)
print("-----")
print("CREATE 2D ARRAY")
b = np.array([[1,2],[3,4]])
print(b)
print("-----")
print("ADDITION")
add = a + 2
print(add)
print("-----")
print("MULTIPLICATION")
mul = a * 2
print(mul)
print("-----")
print("SUM")
print(np.sum(a))
print("-----")
print("MAXIMUM")
print(np.max(a))
print("-----")
print("MINIMUM")
print(np.min(a))
print("-----")
print("ZEROS ARRAY")
c = np.zeros(5)
print(c)
