import numpy as np
import pandas as pd
print("NUMPY PRACTICE")
print("CREATE ARRAY & SUM")
a = np.array([5,10,15,20])
print("Array:",a)
print("Sum:",np.sum(a))
print("------")
print("MAXIMUM AND MINIMUM")
b = np.array([3,7,2,9,5])
print("Maximum:",np.max(b))
print("Minimum:",np.min(b))
print("------")
print("ADDITION AND MULTIPLICATION")
c = np.array([1,2,3])
print("Addition:",c+5)
print("Multiplication:",c*2)
print("------")
print("ZEROS AND ONES")
print("Zeros:",np.zeros(5))
print("Ones:",np.ones(5))
print("================================")
print("PANDAS PRACTICE")
print("CREATE DATAFRAME")
data = {
    "Name":["Ram","Sam","Raj"],
    "Marks":[80,90,85]
}
df = pd.DataFrame(data)
print(df)
print("------")
print("PRINT COLUMN")
print(df["Name"])
print("------")
print("PRINT FIRST ROWS")
print(df.head())
print("------")
print("DATAFRAME INFO")
print(df.info())
