print("create a tuple and print")
a=(1,2,3,4)
print(a)
print("print first element")
a=(1,2,3,4)
print(a[0])
print("print last element")
a=(1,2,3,4)
print(a[-1])
print("loop through tuple")
a=(1,2,3,4)
for i in a:
    print(i)
print("length of the tuple")
a=(1,2,3,4)
print(len(a))
